export const productsObj = {
    controlPanel: [
        {
            _id: 1,
            name: 'ЩУ-ВЕНТ-В-3-К37',
            staticName: 'ЩУ-ВЕНТ-В-3-0,37',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 0.37 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '1.6',
                ratedPowerElectricMotor: '0.37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: 2,
            name: 'ЩУ-ВЕНТ-В-3-2К2',
            staticName: 'ЩУ-ВЕНТ-В-3-2,2',
            ratedEnginePower: '2,2',
            ratedMotorCurrent: '4...6',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 2.2 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '6',
                ratedPowerElectricMotor: '2,2',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: 3,
            name: 'ЩУ-ВЕНТ-В-3-3К',
            staticName: 'ЩУ-ВЕНТ-В-3-3',
            ratedEnginePower: '3',
            ratedMotorCurrent: '7...10',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 3.0 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '10',
                ratedPowerElectricMotor: '3',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: 4,
            name: 'ЩУ-ВЕНТ-В-3-4К',
            staticName: 'ЩУ-ВЕНТ-В-3-4',
            ratedEnginePower: '4',
            ratedMotorCurrent: '7...10',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 4.0 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '10',
                ratedPowerElectricMotor: '4',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: 5,
            name: 'ЩУ-ВЕНТ-В-3-5К5',
            staticName: 'ЩУ-ВЕНТ-В-3-5,5',
            ratedEnginePower: '5,5',
            ratedMotorCurrent: '9...13',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 5.5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '13',
                ratedPowerElectricMotor: '5,5',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: 6,
            name: 'ЩУ-ВЕНТ-В-3-7К5',
            staticName: 'ЩУ-ВЕНТ-В-3-7,5',
            ratedEnginePower: '7,5',
            ratedMotorCurrent: '12...18',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 7.5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '18',
                ratedPowerElectricMotor: '7,5',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: 7,
            name: 'ЩУ-ВЕНТ-В-3-11К',
            staticName: 'ЩУ-ВЕНТ-В-3-11',
            ratedEnginePower: '11',
            ratedMotorCurrent: '16...24',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 11 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '24',
                ratedPowerElectricMotor: '11',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: 8,
            name: 'ЩУ-ВЕНТ-В-3-15К',
            staticName: 'ЩУ-ВЕНТ-В-3-15',
            ratedEnginePower: '15',
            ratedMotorCurrent: '23...32',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 15 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '32',
                ratedPowerElectricMotor: '15',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: 9,
            name: 'ЩУ-ВЕНТ-В-1-ЗМ-К37',
            staticName: 'ЩУ-ВЕНТ-В-1-ЗМ-0,37-пК.УЧ.Ф',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0.37 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (работа только с помощью частотного преобразователя), привод воздушной заслонки, обогрев заслонки, контроль засорения фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '1.6',
                ratedPowerElectricMotor: '0.37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Привод воздушной заслонки????'],
        },
        {
            _id: 10,
            name: 'ЩУ-ВЕНТ-В-1-ЗМ-2К2',
            staticName: 'ЩУ-ВЕНТ-В-1-ЗМ-2,2-пК.УЧ.Ф',
            ratedEnginePower: '2,2',
            ratedMotorCurrent: '4...6',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 2.2 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (работа только с помощью частотного преобразователя), привод воздушной заслонки, обогрев заслонки, контроль засорения фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '6',
                ratedPowerElectricMotor: '2,2',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Привод воздушной заслонки????'],
        },
    ],
}