export const productsObj = {
    controlPanel: [
        {
            _id: '0001',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-3-К37',
            staticName: 'ЩУ-ВЕНТ-В-3-0,37',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 0.37 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '1.6',
                ratedPowerElectricMotor: '0.37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0002',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-3-2К2',
            staticName: 'ЩУ-ВЕНТ-В-3-2,2',
            ratedEnginePower: '2,2',
            ratedMotorCurrent: '4...6',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 2.2 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '6',
                ratedPowerElectricMotor: '2,2',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0003',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-3-3К',
            staticName: 'ЩУ-ВЕНТ-В-3-3',
            ratedEnginePower: '3',
            ratedMotorCurrent: '7...10',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 3.0 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '10',
                ratedPowerElectricMotor: '3',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0004',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-3-4К',
            staticName: 'ЩУ-ВЕНТ-В-3-4',
            ratedEnginePower: '4',
            ratedMotorCurrent: '7...10',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 4.0 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '10',
                ratedPowerElectricMotor: '4',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0005',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-3-5К5',
            staticName: 'ЩУ-ВЕНТ-В-3-5,5',
            ratedEnginePower: '5,5',
            ratedMotorCurrent: '9...13',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 5.5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '13',
                ratedPowerElectricMotor: '5,5',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0006',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-3-7К5',
            staticName: 'ЩУ-ВЕНТ-В-3-7,5',
            ratedEnginePower: '7,5',
            ratedMotorCurrent: '12...18',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 7.5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '18',
                ratedPowerElectricMotor: '7,5',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0007',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-3-11К',
            staticName: 'ЩУ-ВЕНТ-В-3-11',
            ratedEnginePower: '11',
            ratedMotorCurrent: '16...24',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 11 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '24',
                ratedPowerElectricMotor: '11',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0008',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-3-15К',
            staticName: 'ЩУ-ВЕНТ-В-3-15',
            ratedEnginePower: '15',
            ratedMotorCurrent: '23...32',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Релейная логика, Номинальная мощность электродвигателя: 15 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), привод воздушной заслонки ',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '32',
                ratedPowerElectricMotor: '15',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '411x302x145',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-БК', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0009',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-1-ЗМ-К37',
            staticName: 'ЩУ-ВЕНТ-В-1-ЗМ-0,37-пК.УЧ.Ф',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0.37 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '5.2 кг',
                volume: '0.022 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (работа только с помощью частотного преобразователя), привод воздушной заслонки, обогрев заслонки, контроль засорения фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '1.6',
                ratedPowerElectricMotor: '0.37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0010',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-1-ЗМ-2К2',
            staticName: 'ЩУ-ВЕНТ-В-1-ЗМ-2,2-пК.УЧ.Ф',
            ratedEnginePower: '2,2',
            ratedMotorCurrent: '4...6',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 2.2 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (работа только с помощью частотного преобразователя), привод воздушной заслонки, обогрев заслонки, контроль засорения фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '6',
                ratedPowerElectricMotor: '2,2',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0011',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-1-ЗМ-3К',
            staticName: 'ЩУ-ВЕНТ-В-1-ЗМ-3-пК.УЧ.Ф',
            ratedEnginePower: '3',
            ratedMotorCurrent: '7...10',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 3.0 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (работа только с помощью частотного преобразователя), привод воздушной заслонки, обогрев заслонки, контроль засорения фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '10',
                ratedPowerElectricMotor: '3',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0012',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-1-ЗМ-4К',
            staticName: 'ЩУ-ВЕНТ-В-1-ЗМ-4-пК.УЧ.Ф',
            ratedEnginePower: '4',
            ratedMotorCurrent: '7...10',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 4.0 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (работа только с помощью частотного преобразователя), привод воздушной заслонки, обогрев заслонки, контроль засорения фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '10',
                ratedPowerElectricMotor: '4',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0013',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-1-ЗМ-5К5',
            staticName: 'ЩУ-ВЕНТ-В-1-ЗМ-5,5-пК.УЧ.Ф',
            ratedEnginePower: '5,5',
            ratedMotorCurrent: '9...13',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 5.5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (работа только с помощью частотного преобразователя), привод воздушной заслонки, обогрев заслонки, контроль засорения фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '13',
                ratedPowerElectricMotor: '5,5',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0014',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-1-ЗМ-7К5',
            staticName: 'ЩУ-ВЕНТ-В-1-ЗМ-7,5-пК.УЧ.Ф',
            ratedEnginePower: '7,5',
            ratedMotorCurrent: '12...18',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 7.5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (работа только с помощью частотного преобразователя), привод воздушной заслонки, обогрев заслонки, контроль засорения фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '18',
                ratedPowerElectricMotor: '7,5',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0015',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-1-ЗМ-11К',
            staticName: 'ЩУ-ВЕНТ-В-1-ЗМ-11-пК.УЧ.Ф',
            ratedEnginePower: '11',
            ratedMotorCurrent: '16...24',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 11 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (работа только с помощью частотного преобразователя), привод воздушной заслонки, обогрев заслонки, контроль засорения фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '24',
                ratedPowerElectricMotor: '11',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0016',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-В-1-ЗМ-15К',
            staticName: 'ЩУ-ВЕНТ-В-1-ЗМ-15-пК.УЧ.Ф',
            ratedEnginePower: '15',
            ratedMotorCurrent: '23...32',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для вентиляторов, В; Назначение: управление приточной или вытяжной системой вентиляции без теплообменников, управление приводом заслонки; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 15 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для вентиляторов, В',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (работа только с помощью частотного преобразователя), привод воздушной заслонки, обогрев заслонки, контроль засорения фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '32',
                ratedPowerElectricMotor: '15',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0017',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-ВТ-1-ЗМ-0К37',
            staticName: 'ЩУ-ВЕНТ-ВТ-1-ЗМ-0,37',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для приточных систем с водяным нагревателем, ВТ; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя:  0.37 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с водяным нагревателем, ВТ',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), водяной нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '1.6',
                ratedPowerElectricMotor: '0.37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Датчик температуры обратной воды', 'Капиллярный термостат', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0018',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-ВТ-1-ЗМ-2К2',
            staticName: 'ЩУ-ВЕНТ-ВТ-1-ЗМ-2,2',
            ratedEnginePower: '2,2',
            ratedMotorCurrent: '4...6',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для приточных систем с водяным нагревателем, ВТ; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 2.2 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с водяным нагревателем, ВТ',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), водяной нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '6',
                ratedPowerElectricMotor: '2,2',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Датчик температуры обратной воды', 'Капиллярный термостат', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0019',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-ВТ-1-ЗМ-3К',
            staticName: 'ЩУ-ВЕНТ-ВТ-1-ЗМ-3',
            ratedEnginePower: '3',
            ratedMotorCurrent: '7...10',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для приточных систем с водяным нагревателем, ВТ; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 3.0 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с водяным нагревателем, ВТ',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), водяной нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '10',
                ratedPowerElectricMotor: '3',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Датчик температуры обратной воды', 'Капиллярный термостат', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0020',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-ВТ-1-ЗМ-4К',
            staticName: 'ЩУ-ВЕНТ-ВТ-1-ЗМ-4',
            ratedEnginePower: '4',
            ratedMotorCurrent: '7...10',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для приточных систем с водяным нагревателем, ВТ; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 4.0 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с водяным нагревателем, ВТ',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), водяной нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '10',
                ratedPowerElectricMotor: '4',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Датчик температуры обратной воды', 'Капиллярный термостат', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0021',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-ВТ-1-ЗМ-5К5',
            staticName: 'ЩУ-ВЕНТ-ВТ-1-ЗМ-5,5',
            ratedEnginePower: '5,5',
            ratedMotorCurrent: '9...13',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для приточных систем с водяным нагревателем, ВТ; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 5.5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с водяным нагревателем, ВТ',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), водяной нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '13',
                ratedPowerElectricMotor: '5,5',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Датчик температуры обратной воды', 'Капиллярный термостат', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0022',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-ВТ-1-ЗМ-7К5',
            staticName: 'ЩУ-ВЕНТ-ВТ-1-ЗМ-7,5',
            ratedEnginePower: '7,5',
            ratedMotorCurrent: '12...18',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для приточных систем с водяным нагревателем, ВТ; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 7.5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с водяным нагревателем, ВТ',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), водяной нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '18',
                ratedPowerElectricMotor: '7,5',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Датчик температуры обратной воды', 'Капиллярный термостат', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0023',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-ВТ-1-ЗМ-11К',
            staticName: 'ЩУ-ВЕНТ-ВТ-1-ЗМ-11',
            ratedEnginePower: '11',
            ratedMotorCurrent: '16...24',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для приточных систем с водяным нагревателем, ВТ; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 11 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с водяным нагревателем, ВТ',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), водяной нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '24',
                ratedPowerElectricMotor: '11',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Датчик температуры обратной воды', 'Капиллярный термостат', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0024',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТ-ВТ-1-ЗМ-15К',
            staticName: 'ЩУ-ВЕНТ-ВТ-1-ЗМ-15',
            ratedEnginePower: '15',
            ratedMotorCurrent: '23...32',
            maxPermissibleHeaterPower: '0',
            numberOfHeaterStages: 0,
            description: 'Серия: Щиты для приточных систем с водяным нагревателем, ВТ; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 15 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с водяным нагревателем, ВТ',
                warranty: 24,
                weight: '8.4 кг',
                volume: '0.029 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), водяной нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Пластик',
            },
            engineCharacteristics: {
                phaseAndVoltage: '3х400',
                currentFrequency: 50,
                ratedElectricMotor: '32',
                ratedPowerElectricMotor: '15',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '563х302х140',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Датчик температуры обратной воды', 'Капиллярный термостат', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0025',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТп-Э-1-ЗМ-0К35ф-4К5СТ1',
            staticName: 'ЩУ-ВЕНТп-Э-1-ЗМ-0,35ф-4,5/1',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '4,5',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0,35 кВт; Номинальная мощность электрического нагревателя: 4,5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '1.6',
                ratedPowerElectricMotor: '0,37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0026',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТп-Э-1-ЗМ-0К75ф-4К5СТ1',
            staticName: 'ЩУ-ВЕНТп-Э-1-ЗМ-0,75ф-4,5/1',
            ratedEnginePower: '0,75',
            ratedMotorCurrent: '1,6...2,5',
            maxPermissibleHeaterPower: '4,5',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0,75 кВт; Номинальная мощность электрического нагревателя: 4,5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '2.5',
                ratedPowerElectricMotor: '0,75',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0027',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТп-Э-1-ЗМ-0К35ф-6СТ1',
            staticName: 'ЩУ-ВЕНТп-Э-1-ЗМ-0,35ф-6/1',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '6',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0,35 кВт; Номинальная мощность электрического нагревателя: 6 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '1,6',
                ratedPowerElectricMotor: '0,37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0028',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТп-Э-1-ЗМ-0К75ф-6СТ1',
            staticName: 'ЩУ-ВЕНТп-Э-1-ЗМ-0,75ф-6/1',
            ratedEnginePower: '0,75',
            ratedMotorCurrent: '1,6...2,5',
            maxPermissibleHeaterPower: '6',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0,75 кВт; Номинальная мощность электрического нагревателя: 6 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '2,5',
                ratedPowerElectricMotor: '0,75',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0029',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТп-Э-1-ЗМ-0К35ф-7К5СТ1',
            staticName: 'ЩУ-ВЕНТп-Э-1-ЗМ-0,35ф-7,5/1',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '7,5',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0,35 кВт; Номинальная мощность электрического нагревателя: 7,5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '1,6',
                ratedPowerElectricMotor: '0,37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0030',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТп-Э-1-ЗМ-0К75ф-7К5СТ1',
            staticName: 'ЩУ-ВЕНТп-Э-1-ЗМ-0,75ф-7,5/1',
            ratedEnginePower: '0,75',
            ratedMotorCurrent: '1,6...2,5',
            maxPermissibleHeaterPower: '7,5',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0,75 кВт; Номинальная мощность электрического нагревателя: 7,5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '2,5',
                ratedPowerElectricMotor: '0,75',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0031',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТп-Э-1-ЗМ-0К35ф-12СТ1',
            staticName: 'ЩУ-ВЕНТп-Э-1-ЗМ-0,35ф-12/1',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '12',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0,35 кВт; Номинальная мощность электрического нагревателя: 12 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '1,6',
                ratedPowerElectricMotor: '0,37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0032',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТп-Э-1-ЗМ-0К75ф-12СТ1',
            staticName: 'ЩУ-ВЕНТп-Э-1-ЗМ-0,75ф-12/1',
            ratedEnginePower: '0,75',
            ratedMotorCurrent: '1,6...2,5',
            maxPermissibleHeaterPower: '12',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0,75 кВт; Номинальная мощность электрического нагревателя: 12 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '2,5',
                ratedPowerElectricMotor: '0,75',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0033',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТп-Э-1-ЗМ-0К35ф-15СТ1',
            staticName: 'ЩУ-ВЕНТп-Э-1-ЗМ-0,35ф-15/1',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '15',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0,35 кВт; Номинальная мощность электрического нагревателя: 15 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '1,6',
                ratedPowerElectricMotor: '0,37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0034',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТп-Э-1-ЗМ-0К75ф-15СТ1',
            staticName: 'ЩУ-ВЕНТп-Э-1-ЗМ-0,75ф-15/1',
            ratedEnginePower: '0,75',
            ratedMotorCurrent: '1,6...2,5',
            maxPermissibleHeaterPower: '15',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Номинальная мощность электродвигателя: 0,75 кВт; Номинальная мощность электрического нагревателя: 15 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '2,5',
                ratedPowerElectricMotor: '0,75',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0035',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТм-Э-1-ЗМ-0К35-4К5СТ1Т',
            staticName: 'ЩУ-ВЕНТм-Э-1-ЗМ-0,35-4,5/1Т',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '4,5',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Способ регулирования температуры: Плавное, Номинальная мощность электродвигателя: 0,35 кВт; Номинальная мощность электрического нагревателя: 4,5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '1,6',
                ratedPowerElectricMotor: '0,37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0036',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТм-Э-1-ЗМ-0К75-4К5СТ1Т',
            staticName: 'ЩУ-ВЕНТм-Э-1-ЗМ-0,75-4,5/1Т',
            ratedEnginePower: '0,75',
            ratedMotorCurrent: '1,6...2,5',
            maxPermissibleHeaterPower: '4,5',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Способ регулирования температуры: Плавное, Номинальная мощность электродвигателя: 0,75 кВт; Номинальная мощность электрического нагревателя: 4,5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '2,5',
                ratedPowerElectricMotor: '0,75',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0037',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТм-Э-1-ЗМ-0К35-6СТ1Т',
            staticName: 'ЩУ-ВЕНТм-Э-1-ЗМ-0,35-6/1Т',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '6',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Способ регулирования температуры: Плавное, Номинальная мощность электродвигателя: 0,35 кВт; Номинальная мощность электрического нагревателя: 6 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '1,6',
                ratedPowerElectricMotor: '0,37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0038',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТм-Э-1-ЗМ-0К75-6СТ1Т',
            staticName: 'ЩУ-ВЕНТм-Э-1-ЗМ-0,75-6/1Т',
            ratedEnginePower: '0,75',
            ratedMotorCurrent: '1,6...2,5',
            maxPermissibleHeaterPower: '6',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Способ регулирования температуры: Плавное, Номинальная мощность электродвигателя: 0,75 кВт; Номинальная мощность электрического нагревателя: 6 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '2,5',
                ratedPowerElectricMotor: '0,75',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0039',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТм-Э-1-ЗМ-0К35-7К5СТ1Т',
            staticName: 'ЩУ-ВЕНТм-Э-1-ЗМ-0,35-7,5/1Т',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '7,5',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Способ регулирования температуры: Плавное, Номинальная мощность электродвигателя: 0,35 кВт; Номинальная мощность электрического нагревателя: 7,5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '1,6',
                ratedPowerElectricMotor: '0,37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0040',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТм-Э-1-ЗМ-0К75-7К5СТ1Т',
            staticName: 'ЩУ-ВЕНТм-Э-1-ЗМ-0,75-7,5/1Т',
            ratedEnginePower: '0,75',
            ratedMotorCurrent: '1,6...2,5',
            maxPermissibleHeaterPower: '7,5',
            numberOfHeaterStages: 1,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Способ регулирования температуры: Плавное, Номинальная мощность электродвигателя: 0,75 кВт; Номинальная мощность электрического нагревателя: 7,5 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '2,5',
                ratedPowerElectricMotor: '0,75',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0041',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТм-Э-1-ЗМ-0К35-12СТ2Т',
            staticName: 'ЩУ-ВЕНТм-Э-1-ЗМ-0,35-12/2Т',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '12',
            numberOfHeaterStages: 2,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Способ регулирования температуры: Плавное, Номинальная мощность электродвигателя: 0,35 кВт; Номинальная мощность электрического нагревателя: 12 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '1,6',
                ratedPowerElectricMotor: '0,37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0042',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТм-Э-1-ЗМ-0К75-12СТ2Т',
            staticName: 'ЩУ-ВЕНТм-Э-1-ЗМ-0,75-12/2Т',
            ratedEnginePower: '0,75',
            ratedMotorCurrent: '1,6...2,5',
            maxPermissibleHeaterPower: '12',
            numberOfHeaterStages: 2,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Способ регулирования температуры: Плавное, Номинальная мощность электродвигателя: 0,75 кВт; Номинальная мощность электрического нагревателя: 12 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '2,5',
                ratedPowerElectricMotor: '0,75',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0043',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТм-Э-1-ЗМ-0К35-15СТ2Т',
            staticName: 'ЩУ-ВЕНТм-Э-1-ЗМ-0,35-15/2Т',
            ratedEnginePower: '0,37',
            ratedMotorCurrent: '1...1,6',
            maxPermissibleHeaterPower: '15',
            numberOfHeaterStages: 2,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Способ регулирования температуры: Плавное, Номинальная мощность электродвигателя: 0,35 кВт; Номинальная мощность электрического нагревателя: 15 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '1,6',
                ratedPowerElectricMotor: '0,37',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
        {
            _id: '0044',
            image: '',
            price: '',
            name: 'Щит управления ЩУ-ВЕНТм-Э-1-ЗМ-0К75-15СТ2Т',
            staticName: 'ЩУ-ВЕНТм-Э-1-ЗМ-0,75-15/2Т',
            ratedEnginePower: '0,75',
            ratedMotorCurrent: '1,6...2,5',
            maxPermissibleHeaterPower: '15',
            numberOfHeaterStages: 2,
            description: 'Серия: Щиты для приточных систем с электрическим нагревателем, Э; Назначение: Управление приточной системой вентиляции с водяным нагревателем; Принцип управления: Контроллер, Способ регулирования температуры: Плавное, Номинальная мощность электродвигателя: 0,75 кВт; Номинальная мощность электрического нагревателя: 15 кВт.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Щиты управления',
                series: 'Щиты для приточных систем с электрическим нагревателем, Э',
                warranty: 24,
                weight: '21 кг',
                volume: '0.057 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                managedEquipment: 'Двигатель вентилятора (прямой пуск/возможность подключения частотного преобразователя), Электрический нагреватель, привод воздушной заслонки, контроль фильтра',
                housingMaterial: 'Окрашенная сталь',
            },
            engineCharacteristics: {
                phaseAndVoltage: '1х230',
                currentFrequency: 50,
                ratedElectricMotor: '2,5',
                ratedPowerElectricMotor: '0,75',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '600x400x200',
            options: ['Частотный преобразователь', 'Пульт дистанционного управления ПДУ-К', 'Реле перепада давления NDPS500', 'Датчик температуры уличный', 'Датчик температуры канальный', 'Привод воздушной заслонки????'],
        },
    ],
    autoDevice: [
        {
            _id: '0001',
            image: '',
            price: '',
            name: 'Датчик температуры гильзовый TD-G-0-IP54-NTC10k',
            staticName: 'Датчик температуры гильзовый TD-G-0-IP54-NTC10k',
            ratedEnginePower: '',
            ratedMotorCurrent: '',
            maxPermissibleHeaterPower: '',
            numberOfHeaterStages: 0,
            description: 'Серия: Датчики температуры TD; Производитель: Вентикс; Тип: гильзовый; Номинальное сопротивление датчика: 10 кОм; Класс защиты: IP54.',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Приборы автоматики',
                series: 'Датчики температуры TD',
                warranty: 24,
                weight: '0.1 кг',
                volume: '0.0001 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                type: 'гильзовый',
                nominalResistance: '10кОм',
            },
            climaticCharacteristics: {
                temperature: 'до -70 °С',
            },
            overallCharacteristics: '',
            options: [],
        },
        {
            _id: '0002',
            image: '',
            price: '',
            name: 'Пульт управления ЩУ',
            staticName: 'Пульт управления ЩУ',
            ratedEnginePower: '',
            ratedMotorCurrent: '',
            maxPermissibleHeaterPower: '',
            numberOfHeaterStages: 0,
            description: 'Серия: Пульты дистанционного управления',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Приборы автоматики',
                series: 'Пульты дистанционного управления',
                warranty: 24,
                weight: '0.3 кг',
                volume: '0.0005 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                type: '',
                nominalResistance: '',
            },
            climaticCharacteristics: {
                temperature: 'от 5 до 28 °С',
            },
            overallCharacteristics: '',
            options: [],
        },
        {
            _id: '0003',
            image: '',
            price: '',
            name: 'Реле перепада давления PS500',
            staticName: 'Реле перепада давления PS500',
            ratedEnginePower: '',
            ratedMotorCurrent: '',
            maxPermissibleHeaterPower: '',
            numberOfHeaterStages: 0,
            description: 'Серия: Реле перепада давления PS; Диапазон измерения перепада давления: 0-1500',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Приборы автоматики',
                series: 'Реле перепада давления PS',
                warranty: 24,
                weight: '0.2 кг',
                volume: '0.0015 м3',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                type: '',
                nominalResistance: '',
            },
            climaticCharacteristics: {
                temperature: 'до -70 °С',
            },
            overallCharacteristics: '',
            options: [],
        },
        {
            _id: '0004',
            image: '',
            price: '',
            name: 'Частотный преобразователь',
            staticName: 'Частотный преобразователь',
            ratedEnginePower: '',
            ratedMotorCurrent: '',
            maxPermissibleHeaterPower: '',
            numberOfHeaterStages: 0,
            description: '',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Приборы автоматики',
                series: '',
                warranty: 24,
                weight: '',
                volume: '',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                type: '',
                nominalResistance: '',
            },
            climaticCharacteristics: {
                temperature: '',
            },
            overallCharacteristics: '',
            options: [],
        },
        {
            _id: '0005',
            image: '',
            price: '',
            name: 'Пульт дистанционного управления ПДУ-БК',
            staticName: 'Пульт дистанционного управления ПДУ-БК',
            ratedEnginePower: '',
            ratedMotorCurrent: '',
            maxPermissibleHeaterPower: '',
            numberOfHeaterStages: 0,
            description: '',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Приборы автоматики',
                series: '',
                warranty: 24,
                weight: '',
                volume: '',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                type: '',
                nominalResistance: '',
            },
            climaticCharacteristics: {
                temperature: '',
            },
            overallCharacteristics: '',
            options: [],
        },
        {
            _id: '0006',
            image: '',
            price: '',
            name: 'Привод воздушной заслонки',
            staticName: 'Привод воздушной заслонки',
            ratedEnginePower: '',
            ratedMotorCurrent: '',
            maxPermissibleHeaterPower: '',
            numberOfHeaterStages: 0,
            description: '',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Приборы автоматики',
                series: '',
                warranty: 24,
                weight: '',
                volume: '',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                type: '',
                nominalResistance: '',
            },
            climaticCharacteristics: {
                temperature: '',
            },
            overallCharacteristics: '',
            options: [],
        },
        {
            _id: '0007',
            image: '',
            price: '',
            name: 'Пульт дистанционного управления ПДУ-К',
            staticName: 'Пульт дистанционного управления ПДУ-К',
            ratedEnginePower: '',
            ratedMotorCurrent: '',
            maxPermissibleHeaterPower: '',
            numberOfHeaterStages: 0,
            description: '',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Приборы автоматики',
                series: '',
                warranty: 24,
                weight: '',
                volume: '',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                type: '',
                nominalResistance: '',
            },
            climaticCharacteristics: {
                temperature: '',
            },
            overallCharacteristics: '',
            options: [],
        },
        {
            _id: '0008',
            image: '',
            price: '',
            name: 'Датчик температуры уличный',
            staticName: 'Датчик температуры уличный',
            ratedEnginePower: '',
            ratedMotorCurrent: '',
            maxPermissibleHeaterPower: '',
            numberOfHeaterStages: 0,
            description: '',
            characteristic: {
                productGroup: 'Не нужно указывать',
                category: 'Приборы автоматики',
                series: '',
                warranty: 24,
                weight: '',
                volume: '',
                fabricator: 'Schreiman Engineering',
                country: 'Россия',
            },
            designCharacteristics: {
                execution: 'Общепромышленное',
                type: '',
                nominalResistance: '',
            },
            climaticCharacteristics: {
                temperature: '',
            },
            overallCharacteristics: '',
            options: [],
        },
    ],
    regulator: [],
    mixUnits: [],
}